from paper_diff.stage4b_write_executive_summary_llm import ExecutiveSummary
from paper_diff.stage5b_render_executive_briefs import render_briefs


def _summary(grounded: bool = True) -> ExecutiveSummary:
    evidence = [
        {
            "source": "challenger",
            "quote": "Loss is a discounted sum <over> monthly hazards & survival.",
            "why_it_matters": "It prices timing.",
            "grounded": grounded,
        }
    ]
    return ExecutiveSummary(
        headline="Challenger adds lifetime granularity",
        governing_thought="The challenger adds value the champion cannot.",
        recommendation="Pilot it on one portfolio.",
        pillars=[{"claim": f"Pillar {i}.", "evidence": evidence} for i in range(3)],
        challenger_brings=["Discounting.", "Account-level hazards."],
        challenger_lacks=["A long validation window."],
        shared_ground="Both estimate PD.",
        who_should_care="Model risk and the promotion committee.",
        counts={"challenger_only": 69, "champion_only": 99, "shared": 51},
    )


def test_renders_all_three_briefs_with_warning_and_headline():
    briefs = render_briefs(_summary())

    assert set(briefs) == {
        "brief_one_page.html",
        "brief_abstract.html",
        "brief_decision_memo.html",
    }
    for html in briefs.values():
        assert "generated by an LLM" in html
        assert "Challenger adds lifetime granularity" in html
        assert "69" in html


def test_quotes_are_html_escaped():
    briefs = render_briefs(_summary())

    for html in briefs.values():
        assert "&lt;over&gt;" in html
        assert "&amp; survival" in html


def test_ungrounded_evidence_is_badged_and_grounded_is_not():
    badged = render_briefs(_summary(grounded=False))
    clean = render_briefs(_summary(grounded=True))

    for html in badged.values():
        assert "quote not found in comparison" in html
    for html in clean.values():
        assert "quote not found in comparison" not in html
